Update patch set 4
Patch Set 4:

> (1 comment)
 > 
 > After USE_EXTERNAL_REPO, this CL and http://r.android.com/119304
 > I'm getting this when trying to compile. Any ideas what's wrong?
 > 
 > Feel free to merge this CL when I'm asleep and continue with any
 > additional fixes.
 > 
 > General error during conversion: java.lang.NoClassDefFoundError:
 > com/android/build/gradle/api/AndroidSourceSet
 > 
 > java.lang.RuntimeException: java.lang.NoClassDefFoundError:
 > com/android/build/gradle/api/AndroidSourceSet
 > at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1083)
 > at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1061)
 > at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:583)
 > at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:561)
 > at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:538)
 > at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:517)
 > at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:122)
 > at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:47)
 > at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:53)
 > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 > at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 > at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 > at java.lang.reflect.Method.invoke(Method.java:597)
 > at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
 > at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
 > at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
 > at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
 > at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
 > at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
 > at java.lang.Thread.run(Thread.java:662)
 > Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/api/AndroidSourceSet
 > at java.lang.ClassLoader.defineClass1(Native Method)
 > at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
 > at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
 > at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
 > at org.gradle.internal.classloader.TransformingClassLoader.findClass(TransformingClassLoader.java:50)
 > ...

Try doing a clean.  I'm not sure what caused this, but I do see it from time to time.

Patch-set: 4
Label: Verified=0